# Generated by Django 2.2.3 on 2019-07-26 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('description', models.CharField(max_length=128)),
                ('width', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('solar_requirements', models.CharField(choices=[('FS', 'Full Sun'), ('PS', 'Partial Sun'), ('SH', 'Shaded')], default='FS', max_length=2)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'date_modified'),
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this plant', max_length=256)),
                ('solar_requirement', models.CharField(choices=[('FS', 'Full Sun'), ('PS', 'Partial Sun'), ('SH', 'Shaded')], max_length=2)),
                ('plant_separation', models.SmallIntegerField()),
                ('planting_depth', models.SmallIntegerField()),
                ('days_to_germinate', models.SmallIntegerField()),
                ('days_to_harvest', models.SmallIntegerField()),
                ('day_planted', models.DateField()),
                ('beds', models.ManyToManyField(to='garden.Bed')),
            ],
            options={
                'ordering': ('plant_separation', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gardener', models.ForeignKey(help_text="This garden's caretaker.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Garden'),
        ),
    ]
